config/routes.rb
Rails.application.routes.draw do
  get 'users/spotify'

  resources :tracks
  resources :playlists

  get 'playlist/update_all', to: 'playlists#update_all_new_tracks'

  root 'playlists#landing_page'

  get '/auth/spotify/callback', to: 'users#spotify'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :tracks

  def destroy
    self.tracks.destroy_all
    super
  end

  def owner_and_creator?(own, cre)
    owner==own && creator==cre
  end

  def formatted_creator
    creator.split(':')[2] if creator.include? ':'
  end

  def formatted_uri
    uri.split(':')[4]
  end

  def formatted_owner
    owner.split(':')[2]
  end

  def update_discover user
    new_pl = RSpotify::Playlist.new(RSpotify.get("https://api.spotify.com/v1/users/spotify/playlists/#{formatted_uri}"))
      # debugger
      if new_pl.tracks_added_at.first.last >= Playlist.find_by_ptype("discover_weekly").updated_at  && Playlist.find_by_name("Discover Weekly #{(new_pl.tracks_added_at.first.last-1.week).strftime("%m/%d/%Y")}").nil?
        create_old_dw(new_pl.tracks_added_at.first.last-1.week, user)
        self.tracks = [] #nils the pls's current tracks
        new_pl.tracks.each do |t| #adds all of the new, pulled tracks to the local pl
          track = Track.new
          track.uri = t.uri
          track.name = t.name
          self.tracks << track
        end
        # debugger
      end
  end

  def add_remove_tracks user
    new_pl=RSpotify::Playlist.find(formatted_creator, formatted_uri)
    puts "Updated playlist size #{new_pl.tracks.size}"
    puts "Old playlist size #{tracks.size}"
    #Below works for both removed AND added tracks rn
    diff_tracks = compare_tracks(tracks.map{|t| t.uri}, new_pl.tracks.map{|t| t.uri})
    # debugger if name=="Test PL"
    if diff_tracks!=-1
      if !diff_tracks[:removed_tracks].empty?
        rmv_tracks_pl = Playlist.where(name: "#{name} -- Removed Tracks", ptype: "removed_tracks") #checks if a 'removed_tracks' playlist has already been created for this playlist
        # debugger
        if rmv_tracks_pl.empty?
          create_removed_song_pl(diff_tracks[:removed_tracks], self, user)
        else
          add_to_remove_tracks(rmv_tracks_pl.first, diff_tracks[:removed_tracks], user)
        end
        self.tracks = [] #nils the pls's current tracks
        new_pl.tracks.each do |t| #adds all of the new, pulled tracks to the local pl
          track = Track.new
          track.uri = t.uri
          track.name = t.name
          self.tracks << track
        end
        # debugger
        puts "Current playlist size #{tracks.size}"
      end
      if !diff_tracks[:added_tracks].empty?
        add_to_original_tracks(self, diff_tracks[:added_tracks])
      end
    end
  end

  def self.convert_playlist (rs_playlist, current_user_uri)
    pl = Playlist.new
    pl.uri = rs_playlist.uri
    pl.name = rs_playlist.name
    pl.creator = rs_playlist.owner.uri #owner of the ORIGINAL playlist, not the current user
    pl.tracking = true
    pl.gen_new_list = false
    pl.owner = current_user_uri
    pl.ptype = "original"
    pl.ptype = "discover_weekly" if rs_playlist.name == "Discover Weekly"
    pl.image_url = rs_playlist.images.first["url"]
    rs_playlist.tracks.each do |t|
      track = Track.new
      track.uri = t.uri
      track.name = t.name
      pl.tracks << track
    end
    pl.save
  end

  private

    def create_old_dw(time, user)
      pl = Playlist.new
      pl.name = "Discover Weekly #{time.strftime("%m/%d/%Y")}"
      pl.creator = "spotify:user:spotify" #owner of the ORIGINAL playlist, not the current user
      pl.tracking = false
      pl.gen_new_list = false
      pl.owner = owner
      pl.ptype = "removed_tracks"
      self.tracks.each do |t|
        track = Track.new
        track.uri = t.uri
        track.name = t.name
        pl.tracks << track
      end
      spotify_pl = create_spotify_pl(pl, user)
      pl.uri = spotify_pl.uri #creates the playlist on spotify and returns its uri
      pl.image_url = spotify_pl.images.first["url"] if !spotify_pl.images.empty?
      pl.save
    end

    def add_to_remove_tracks(playlist, new_tracks, user) #adds the tracks remotely as well
      RSpotify.authenticate("<>", "<>")
      pl_track_uris = playlist.tracks.map{|t| t.uri}
      # debugger
      new_tracks.each do |t|
        if !pl_track_uris.include? t
          track = Track.new
          track.uri = t
          track.name = RSpotify::Track.find(t.split(':')[2]).name
          add_spotify_track([]<<RSpotify::Track.find(t.split(':')[2]), playlist.formatted_uri, user.id)
          playlist.tracks << track
        end
      end
      playlist.save
    end

    def add_to_original_tracks(playlist, new_tracks) #only adds the tracks locally
      RSpotify.authenticate("<>", "<>")
      pl_track_uris = playlist.tracks.map{|t| t.uri}
      # debugger
      new_tracks.each do |t|
        if !pl_track_uris.include? t
          track = Track.new
          track.uri = t
          track.name = RSpotify::Track.find(t.split(':')[2]).name
          playlist.tracks << track
        end
      end
      playlist.save
    end

    def create_removed_song_pl(track_uris, parent_playlist, user)
      playlist = Playlist.new
      playlist.name = "#{parent_playlist.name} -- Removed Tracks"
      playlist.creator = parent_playlist.creator
      playlist.tracking = true
      playlist.gen_new_list = false
      playlist.owner = parent_playlist.owner
      playlist.ptype = "removed_tracks"
      track_uris.each do |t|
        track = Track.new
        track.uri = t
        track.name = RSpotify::Track.find(t.split(':')[2]).name
        playlist.tracks << track
      end
      # debugger
      spotify_pl = create_spotify_pl(playlist, user)
      playlist.uri = spotify_pl.uri #creates the playlist on spotify and returns its uri
      playlist.image_url = spotify_pl.images.first["url"] if !spotify_pl.images.empty?
      playlist.save
    end

    def create_spotify_pl(local_playlist, user)
      RSpotify.authenticate("<>", "<>")
      playlist = user.create_playlist!(local_playlist.name)
      tracks = local_playlist.tracks.map{|t| RSpotify::Track.find(t.formatted_uri)}.reverse
      # debugger
      playlist.add_tracks!(tracks) if !tracks.empty?
      playlist
    end

    def add_spotify_track(track, pl_uri, user_name)
      RSpotify.authenticate("<>", "<>")
      RSpotify::Playlist.find(user_name, pl_uri).add_tracks!(track)
    end

    def compare_tracks(old_pl_uris, new_pl_uris) #this doesn't get duplicate songs! Should be fine, is an edge case
      removed_tracks = old_pl_uris.select{|i| !new_pl_uris.include? i} #(old_pl_uris+new_pl_uris).select{ |t| (old_pl_uris+new_pl_uris).count(t)==1}
      added_tracks = new_pl_uris.select{|i| !old_pl_uris.include? i}
      # debugger
      puts "Amount of removed tracks found #{removed_tracks.count}"
      removed_tracks.empty? && added_tracks.empty? ? -1 : {removed_tracks: removed_tracks, added_tracks: added_tracks}
       #could delete, but like the puts for rn
      # new_tracks = new_pl_uris.reject{ |i| old_pl_uris.include? i}
      # # {removed_tracks: removed_tracks, new_tracks: new_tracks}
      # removed_tracks
    end
end

app/controllers/playlists_controller.rb
require 'rspotify'

class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.tracks.destroy_all
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def landing_page
  end

  def update_all_new_tracks
    current_user_uri = RSpotify::User.new(YAML::load session[:user_hash]).uri
    pls = Playlist.all
    pls.each do |playlist|
      puts "The big three: #{playlist.ptype}, #{playlist.tracking}, #{playlist.owner}, and #{current_user_uri} "
      playlist.add_remove_tracks RSpotify::User.new(YAML::load session[:user_hash]) if playlist.ptype=="original" && playlist.tracking && playlist.owner==current_user_uri
      playlist.update_discover RSpotify::User.new(YAML::load session[:user_hash]) if playlist.ptype=="discover_weekly"
    end
    @your_playlists = Playlist.where(owner: current_user_uri).order(tracking: :desc, updated_at: :asc)
    render "users/spotify.html.erb"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:uri, :name, :creator, :owner, :tracking, :gen_new_list)
    end



end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for(playlist) do |f| %>
  <% if playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uri %>
    <%= f.text_field :uri %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :creator %>
    <%= f.text_field :creator %>
  </div>

  <div class="field">
    <%= f.label :tracking %>
    <%= f.text_field :tracking %>
  </div>

  <div class="field">
    <%= f.label :gen_new_list %>
    <%= f.check_box :gen_new_list %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Sign in with Spotify', '/auth/spotify' %>
<%= link_to 'Update Pls', '/playlist/update_all', :method => :patch %>

<h1>Playlists</h1>

<table>
  <thead>
    <tr>
      <th>Uri</th>
      <th>Name</th>
      <th>Creator</th>
      <th>Owner</th>
      <th>Tracking</th>
      <th>Gen new list</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.uri %></td>
        <td><%= playlist.name %></td>
        <td><%= playlist.creator %></td>
          <td><%= playlist.owner %></td>
        <td><%= playlist.tracking %></td>
        <td><%= playlist.gen_new_list %></td>
        <td><%= playlist.ptype %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/landing_page.html.erb
<div id="main" >
  <h2 >Welcome to <span class="title">Trackify!</span></h2>
  <h4>Forgot to save your favorite song <br> before it was taken off a playlist? Lost another <br> Discover Weekly because it slipped your mind?  <br> </h4>

    <h3 style="color: #4763f9">Worry no longer! </h3>
  <h4><span class="title">Trackify</span> is an app that tracks changes in your Spotify playlists, <br> updating or generating a new playlist when songs are added/removed.<br> Never lose a Discover Weekly again!</h4>

  <h4>Log in to start tracking!</h4>
  <%= link_to image_tag('spotify_login.png'), '/auth/spotify' %>
</div>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uri:</strong>
  <%= @playlist.uri %>
</p>

<p>
  <strong>Name:</strong>
  <%= @playlist.name %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @playlist.creator %>
</p>

<p>
  <strong>Tracking:</strong>
  <%= @playlist.tracking %>
</p>

<p>
  <strong>Playlist Type:</strong>
  <%= @playlist.ptype %>
</p>

<table>
  <tr>
    <td>Track Name</td>
    <td>Track URI</td>
  </tr>
  <% @playlist.tracks.each do |t| %>
    <tr>
      <td><%=t.name%></td>
      <td><%=t.uri%></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>